### ISSUE TITLE
mark parser doesn't conform to the Markdown specification

### ISSUE THREAD

**Issue by xor-gate** [a8m/mark#7]
The parsing/rendering is broken for e.g 

```
`my_variable_one`
```

which renders to

```
<code>my<em>variable</em>one</code>
```

it should

```
<code>my_variable_one</code>
```

My suggestion is to put the project in archive mode as it is not maintained since 2017 and link to a compliant tool like https://github.com/russross/blackfriday-tool

Kind regards,
Jerry

**Comment by a8m** [comment]
done. thanks
